name: Sync Notion to GitHub

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install @notionhq/client
      
      - name: Sync Notion pages
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }} 
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }} 
        run: node js/sync-notion.js
      
      - name: Commit changes
        run: |
          git config user.name "Notion Sync Bot"
          git config user.email "bot@globalmix.online"
          git add .
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "Sync from Notion $(date +'%Y-%m-%d %H:%M')"
          git push
